all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: "{{ lookup('env', 'DEPLOY_USER') }}"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    app_servers:
      hosts:
        211-civic-platform:
          ansible_host: "{{ lookup('env', 'APP_SERVER_IP') }}"
    security_servers:
      hosts:
        211-security:
          ansible_host: "{{ lookup('env', 'SECURITY_SERVER_IP') }}"
