---
- name: Deploy per-service environment files
  hosts: app_servers
  become: yes
  vars_files:
    - ../vars/secrets.yml

  tasks:

    - name: Deploy gateway env
      template:
        src: ../templates/env.gateway.j2
        dest: "/home/deploy/211/.env.gateway"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy request-service env
      template:
        src: ../templates/env.request-service.j2
        dest: "/home/deploy/211/.env.request-service"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy notification-service env
      template:
        src: ../templates/env.notification-service.j2
        dest: "/home/deploy/211/.env.notification-service"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy location-service env
      template:
        src: ../templates/env.location-service.j2
        dest: "/home/deploy/211/.env.location-service"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy ticket-service env
      template:
        src: ../templates/env.ticket-service.j2
        dest: "/home/deploy/211/.env.ticket-service"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy postgres env
      template:
        src: ../templates/env.postgres.j2
        dest: "/home/deploy/211/.env.postgres"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true

    - name: Deploy rabbitmq env
      template:
        src: ../templates/env.rabbitmq.j2
        dest: "/home/deploy/211/.env.rabbitmq"
        owner: "deploy"
        group: "deploy"
        mode: '0600'
      no_log: true
